### ISSUE TITLE
This is the best color picker ever on windows!!

### ISSUE THREAD

**Issue by riccardogiorato** [bluegrams/Colora#3]
This is the best color picker ever on windows!!

All the other alterantives don't work with new version of windows but yours is perfect!

Thank you very much for your work!

**Comment by alxnull** [comment]
Thanks for the kind words. :)
I would really appreciate it if you could add your opinion to Sourceforge (https://sourceforge.net/projects/colora/reviews) or AlternativeTo (https://alternativeto.net/software/colora/).

(And always feel free to make suggestions what features I could improve or add.)
