### ISSUE TITLE
Feature request: Open when Windows call Color picker API

### ISSUE THREAD

**Issue by myhrmans** [bluegrams/Colora#4]
Hi, it would be amazing if this opend instead of windows old color picker. 

There are other applications that can do this but they are all abandoned..

[See this thread ](https://superuser.com/questions/1412770/how-to-change-the-windows-10-default-color-picker)

**Comment by alxnull** [comment]
Thanks for your suggestion. I'm afraid this is out of the scope of this app at the moment.

**Comment by neoOpus** [comment]
> Thanks for your suggestion. I'm afraid this is out of the scope of this app at the moment.

But this is the only feature that would make this shift from Yet Another Color Picker to The Color Picker...

Jovian Color Picker do it, but it is a paid (that you cannot pay for anymore) abandonware.
